# Generated by Django 4.2.1 on 2023-09-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deposits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposits",
            name="amount",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
