# Generated by Django 4.1.7 on 2023-09-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Customers", "0002_alter_customers_ghana_card_number"),
        ("deposits", "0002_alter_deposits_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposits",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deposits",
                to="Customers.customers",
            ),
        ),
    ]
