# Generated by Django 4.2.1 on 2023-09-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="ghana_card_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
