# Generated by Django 4.2.1 on 2023-09-27 16:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Customers", "0002_alter_customers_ghana_card_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("teller_id", models.CharField(blank=True, max_length=255, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("transaction_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        choices=[("deposit", "deposit"), ("withdrawal", "withdrawal")],
                        default="deposit",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="Customers.customers",
                    ),
                ),
            ],
        ),
    ]
