# Generated by Django 4.2.1 on 2023-09-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="Customers.customers",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amount", models.FloatField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
