# Generated by Django 4.2.1 on 2023-09-27 16:07

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="account_number",
            field=models.CharField(
                blank=True,
                default=accounts.utils.generate_account_number,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="amount",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
